"""add_events_assignments_competitions

Revision ID: 60bde5b1fb1a
Revises: 005_notifications_admin
Create Date: 2026-09-03 23:03:23.801545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bde5b1fb1a'
down_revision: Union[str, None] = '005_notifications_admin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOTE: all app enums use native_enum=False (VARCHAR + CHECK, no PG TYPE).
    # Earlier autogenerate emitted native native enums which fail on fresh DB
    # with `type "application_status_enum" does not exist`. Keep as VARCHAR.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_events', 'status',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'WITHDRAWN', name='application_status_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'WITHDRAWN', name='application_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'APPLIED'::character varying"))
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='interview_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PLACEMENT', 'INTERVIEW', 'SYSTEM', 'COMMUNITY', name='notification_type_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PLACEMENT'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('STUDENT', 'ADMIN', 'TPO', name='role_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'ADMIN', 'TPO', name='role_enum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('PLACEMENT', 'INTERVIEW', 'SYSTEM', 'COMMUNITY', name='notification_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False,
               existing_server_default=sa.text("'PLACEMENT'::character varying"))
    op.alter_column('interviews', 'status',
               existing_type=sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='interview_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False,
               existing_server_default=sa.text("'SCHEDULED'::character varying"))
    op.alter_column('applications', 'status',
               existing_type=sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'WITHDRAWN', name='application_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False,
               existing_server_default=sa.text("'APPLIED'::character varying"))
    op.alter_column('application_events', 'status',
               existing_type=sa.Enum('APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'INTERVIEW_SCHEDULED', 'OFFERED', 'REJECTED', 'WITHDRAWN', name='application_status_enum', native_enum=False),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    # ### end Alembic commands ###
